version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql


  app:
    build:
      context: .
    image: dev
    container_name: dev-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stationSki
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - "9090:9090"
    networks:
      - app-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app-network
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  grafana_data:
